-- =====================================================================
-- Migration 002: edgar_codes
-- Date:   2026-09-02
-- Revert: db/revert_002.sql
--
-- EDGAR writes locations as its own two-character codes: E9, N4, A1, 2M.
-- Nothing downstream can read those, and a routed-out company showing 'E9'
-- explains nothing. This table is where the code-to-name mapping lives, so
-- every route-out and every funnel row can name the actual place.
--
-- Seeded verbatim from the capture at
--   docs/sources/edgar_state_country_codes_2026-09-02.txt
-- fetched https://www.sec.gov/submit-filings/filer-support-resources/edgar-state-country-codes on 2026-09-02. No code is inferred.
-- =====================================================================

create table if not exists edgar_codes (
    code        text primary key,
    label       text not null,
    kind        text not null,
    source_url  text,
    captured_on date,
    constraint edgar_codes_kind_chk check (kind in ('us_state', 'foreign'))
);

insert into edgar_codes (code, label, kind) values
 ('1A','Anguilla','foreign'),
 ('1B','Armenia','foreign'),
 ('1C','Aruba','foreign'),
 ('1D','Azerbaijan','foreign'),
 ('1E','Bosnia And Herzegovina','foreign'),
 ('1F','Belarus','foreign'),
 ('1G','Djibouti','foreign'),
 ('1H','Estonia','foreign'),
 ('1J','Eritrea','foreign'),
 ('1K','Micronesia, Federated States Of','foreign'),
 ('1L','South Georgia And The South Sandwich Islands','foreign'),
 ('1M','Croatia','foreign'),
 ('1N','Kyrgyzstan','foreign'),
 ('1P','Kazakstan','foreign'),
 ('1Q','Lithuania','foreign'),
 ('1R','Latvia','foreign'),
 ('1S','Moldova, Republic Of','foreign'),
 ('1T','Marshall Islands','foreign'),
 ('1U','Macedonia, The Former Yugoslav Republic Of','foreign'),
 ('1V','Northern Mariana Islands','foreign'),
 ('1W','New Caledonia','foreign'),
 ('1X','Palestinian Territory, Occupied','foreign'),
 ('1Y','Palau','foreign'),
 ('1Z','Russian Federation','foreign'),
 ('2A','Slovenia','foreign'),
 ('2B','Slovakia','foreign'),
 ('2C','French Southern Territories','foreign'),
 ('2D','Tajikistan','foreign'),
 ('2E','Turkmenistan','foreign'),
 ('2G','Tuvalu','foreign'),
 ('2H','Ukraine','foreign'),
 ('2J','United States Minor Outlying Islands','foreign'),
 ('2K','Uzbekistan','foreign'),
 ('2L','Vanuatu','foreign'),
 ('2M','Germany','foreign'),
 ('2N','Czech Republic','foreign'),
 ('2P','Mayotte','foreign'),
 ('2Q','Georgia','foreign'),
 ('A0','Alberta, Canada','foreign'),
 ('A1','British Columbia, Canada','foreign'),
 ('A2','Manitoba, Canada','foreign'),
 ('A3','New Brunswick, Canada','foreign'),
 ('A4','Newfoundland, Canada','foreign'),
 ('A5','Nova Scotia, Canada','foreign'),
 ('A6','Ontario, Canada','foreign'),
 ('A7','Prince Edward Island, Canada','foreign'),
 ('A8','Quebec, Canada','foreign'),
 ('A9','Saskatchewan, Canada','foreign'),
 ('AK','Alaska','us_state'),
 ('AL','Alabama','us_state'),
 ('AR','Arkansas','us_state'),
 ('AZ','Arizona','us_state'),
 ('B0','Yukon, Canada','foreign'),
 ('B1','Botswana','foreign'),
 ('B2','Afghanistan','foreign'),
 ('B3','Albania','foreign'),
 ('B4','Algeria','foreign'),
 ('B5','American Samoa','foreign'),
 ('B6','Andorra','foreign'),
 ('B7','Angola','foreign'),
 ('B8','Antarctica','foreign'),
 ('B9','Antigua And Barbuda','foreign'),
 ('C0','United Arab Emirates','foreign'),
 ('C1','Argentina','foreign'),
 ('C3','Australia','foreign'),
 ('C4','Austria','foreign'),
 ('C5','Bahamas','foreign'),
 ('C6','Bahrain','foreign'),
 ('C7','Bangladesh','foreign'),
 ('C8','Barbados','foreign'),
 ('C9','Belgium','foreign'),
 ('CA','California','us_state'),
 ('CO','Colorado','us_state'),
 ('CT','Connecticut','us_state'),
 ('D0','Bermuda','foreign'),
 ('D1','Belize','foreign'),
 ('D2','Bhutan','foreign'),
 ('D3','Bolivia','foreign'),
 ('D4','Bouvet Island','foreign'),
 ('D5','Brazil','foreign'),
 ('D6','British Indian Ocean Territory','foreign'),
 ('D7','Solomon Islands','foreign'),
 ('D8','Virgin Islands, British','foreign'),
 ('D9','Brunei Darussalam','foreign'),
 ('DC','District Of Columbia','us_state'),
 ('DE','Delaware','us_state'),
 ('E0','Bulgaria','foreign'),
 ('E1','Myanmar','foreign'),
 ('E2','Burundi','foreign'),
 ('E3','Cambodia','foreign'),
 ('E4','Cameroon','foreign'),
 ('E8','Cape Verde','foreign'),
 ('E9','Cayman Islands','foreign'),
 ('F0','Central African Republic','foreign'),
 ('F1','Sri Lanka','foreign'),
 ('F2','Chad','foreign'),
 ('F3','Chile','foreign'),
 ('F4','China','foreign'),
 ('F5','Taiwan','foreign'),
 ('F6','Christmas Island','foreign'),
 ('F7','Cocos (Keeling) Islands','foreign'),
 ('F8','Colombia','foreign'),
 ('F9','Comoros','foreign'),
 ('FL','Florida','us_state'),
 ('G0','Congo','foreign'),
 ('G1','Cook Islands','foreign'),
 ('G2','Costa Rica','foreign'),
 ('G3','Cuba','foreign'),
 ('G4','Cyprus','foreign'),
 ('G6','Benin','foreign'),
 ('G7','Denmark','foreign'),
 ('G8','Dominican Republic','foreign'),
 ('G9','Dominica','foreign'),
 ('GA','Georgia','us_state'),
 ('GU','Guam','us_state'),
 ('H1','Ecuador','foreign'),
 ('H2','Egypt','foreign'),
 ('H3','El Salvador','foreign'),
 ('H4','Equatorial Guinea','foreign'),
 ('H5','Ethiopia','foreign'),
 ('H6','Faroe Islands','foreign'),
 ('H7','Falkland Islands (Malvinas)','foreign'),
 ('H8','Fiji','foreign'),
 ('H9','Finland','foreign'),
 ('HI','Hawaii','us_state'),
 ('I0','France','foreign'),
 ('I3','French Guiana','foreign'),
 ('I4','French Polynesia','foreign'),
 ('I5','Gabon','foreign'),
 ('I6','Gambia','foreign'),
 ('IA','Iowa','us_state'),
 ('ID','Idaho','us_state'),
 ('IL','Illinois','us_state'),
 ('IN','Indiana','us_state'),
 ('J0','Ghana','foreign'),
 ('J1','Gibraltar','foreign'),
 ('J2','Kiribati','foreign'),
 ('J3','Greece','foreign'),
 ('J4','Greenland','foreign'),
 ('J5','Grenada','foreign'),
 ('J6','Guadeloupe','foreign'),
 ('J8','Guatemala','foreign'),
 ('J9','Guinea','foreign'),
 ('K0','Guyana','foreign'),
 ('K1','Haiti','foreign'),
 ('K2','Honduras','foreign'),
 ('K3','Hong Kong','foreign'),
 ('K4','Heard Island And Mcdonald Islands','foreign'),
 ('K5','Hungary','foreign'),
 ('K6','Iceland','foreign'),
 ('K7','India','foreign'),
 ('K8','Indonesia','foreign'),
 ('K9','Iran, Islamic Republic Of','foreign'),
 ('KS','Kansas','us_state'),
 ('KY','Kentucky','us_state'),
 ('L0','Iraq','foreign'),
 ('L2','Ireland','foreign'),
 ('L3','Israel','foreign'),
 ('L6','Italy','foreign'),
 ('L7','Cote D''Ivoire','foreign'),
 ('L8','Jamaica','foreign'),
 ('L9','Svalbard And Jan Mayen','foreign'),
 ('LA','Louisiana','us_state'),
 ('M0','Japan','foreign'),
 ('M2','Jordan','foreign'),
 ('M3','Kenya','foreign'),
 ('M4','Korea, Democratic People''S Republic Of','foreign'),
 ('M5','Korea, Republic Of','foreign'),
 ('M6','Kuwait','foreign'),
 ('M7','Lao People''S Democratic Republic','foreign'),
 ('M8','Lebanon','foreign'),
 ('M9','Lesotho','foreign'),
 ('MA','Massachusetts','us_state'),
 ('MD','Maryland','us_state'),
 ('ME','Maine','us_state'),
 ('MI','Michigan','us_state'),
 ('MN','Minnesota','us_state'),
 ('MO','Missouri','us_state'),
 ('MS','Mississippi','us_state'),
 ('MT','Montana','us_state'),
 ('N0','Liberia','foreign'),
 ('N1','Libyan Arab Jamahiriya','foreign'),
 ('N2','Liechtenstein','foreign'),
 ('N4','Luxembourg','foreign'),
 ('N5','Macau','foreign'),
 ('N6','Madagascar','foreign'),
 ('N7','Malawi','foreign'),
 ('N8','Malaysia','foreign'),
 ('N9','Maldives','foreign'),
 ('NC','North Carolina','us_state'),
 ('ND','North Dakota','us_state'),
 ('NE','Nebraska','us_state'),
 ('NH','New Hampshire','us_state'),
 ('NJ','New Jersey','us_state'),
 ('NM','New Mexico','us_state'),
 ('NV','Nevada','us_state'),
 ('NY','New York','us_state'),
 ('O0','Mali','foreign'),
 ('O1','Malta','foreign'),
 ('O2','Martinique','foreign'),
 ('O3','Mauritania','foreign'),
 ('O4','Mauritius','foreign'),
 ('O5','Mexico','foreign'),
 ('O9','Monaco','foreign'),
 ('OH','Ohio','us_state'),
 ('OK','Oklahoma','us_state'),
 ('OR','Oregon','us_state'),
 ('P0','Mongolia','foreign'),
 ('P1','Montserrat','foreign'),
 ('P2','Morocco','foreign'),
 ('P3','Mozambique','foreign'),
 ('P4','Oman','foreign'),
 ('P5','Nauru','foreign'),
 ('P6','Nepal','foreign'),
 ('P7','Netherlands','foreign'),
 ('P8','Netherlands Antilles','foreign'),
 ('PA','Pennsylvania','us_state'),
 ('PR','Puerto Rico','us_state'),
 ('Q1','Viet Nam','foreign'),
 ('Q2','New Zealand','foreign'),
 ('Q3','Nicaragua','foreign'),
 ('Q4','Niger','foreign'),
 ('Q5','Nigeria','foreign'),
 ('Q6','Niue','foreign'),
 ('Q7','Norfolk Island','foreign'),
 ('Q8','Norway','foreign'),
 ('R0','Pakistan','foreign'),
 ('R1','Panama','foreign'),
 ('R2','Papua New Guinea','foreign'),
 ('R4','Paraguay','foreign'),
 ('R5','Peru','foreign'),
 ('R6','Philippines','foreign'),
 ('R8','Pitcairn','foreign'),
 ('R9','Poland','foreign'),
 ('RI','Rhode Island','us_state'),
 ('S0','Guinea-Bissau','foreign'),
 ('S1','Portugal','foreign'),
 ('S3','Qatar','foreign'),
 ('S4','Reunion','foreign'),
 ('S5','Romania','foreign'),
 ('S6','Rwanda','foreign'),
 ('S8','San Marino','foreign'),
 ('S9','Sao Tome And Principe','foreign'),
 ('SC','South Carolina','us_state'),
 ('SD','South Dakota','us_state'),
 ('T0','Saudi Arabia','foreign'),
 ('T1','Senegal','foreign'),
 ('T2','Seychelles','foreign'),
 ('T3','South Africa','foreign'),
 ('T6','Namibia','foreign'),
 ('T7','Yemen','foreign'),
 ('T8','Sierra Leone','foreign'),
 ('TN','Tennessee','us_state'),
 ('TX','Texas','us_state'),
 ('U0','Singapore','foreign'),
 ('U1','Somalia','foreign'),
 ('U3','Spain','foreign'),
 ('U5','Western Sahara','foreign'),
 ('U7','Saint Kitts And Nevis','foreign'),
 ('U8','Saint Helena','foreign'),
 ('U9','Saint Lucia','foreign'),
 ('UT','Utah','us_state'),
 ('V0','Saint Pierre And Miquelon','foreign'),
 ('V1','Saint Vincent And The Grenadines','foreign'),
 ('V2','Sudan','foreign'),
 ('V3','Suriname','foreign'),
 ('V6','Swaziland','foreign'),
 ('V7','Sweden','foreign'),
 ('V8','Switzerland','foreign'),
 ('V9','Syrian Arab Republic','foreign'),
 ('VA','Virginia','us_state'),
 ('VI','Virgin Islands, U.S.','us_state'),
 ('VT','Vermont','us_state'),
 ('W0','Tanzania, United Republic Of','foreign'),
 ('W1','Thailand','foreign'),
 ('W2','Togo','foreign'),
 ('W3','Tokelau','foreign'),
 ('W4','Tonga','foreign'),
 ('W5','Trinidad And Tobago','foreign'),
 ('W6','Tunisia','foreign'),
 ('W7','Turks And Caicos Islands','foreign'),
 ('W8','Turkey','foreign'),
 ('W9','Uganda','foreign'),
 ('WA','Washington','us_state'),
 ('WI','Wisconsin','us_state'),
 ('WV','West Virginia','us_state'),
 ('WY','Wyoming','us_state'),
 ('X0','United Kingdom','foreign'),
 ('X1','United States','foreign'),
 ('X2','Burkina Faso','foreign'),
 ('X3','Uruguay','foreign'),
 ('X4','Holy See (Vatican City State)','foreign'),
 ('X5','Venezuela','foreign'),
 ('X8','Wallis And Futuna','foreign'),
 ('XX','Unknown','foreign'),
 ('Y0','Samoa','foreign'),
 ('Y3','Congo, The Democratic Republic Of The','foreign'),
 ('Y4','Zambia','foreign'),
 ('Y5','Zimbabwe','foreign'),
 ('Y6','Aland Islands','foreign'),
 ('Y7','Guernsey','foreign'),
 ('Y8','Isle Of Man','foreign'),
 ('Y9','Jersey','foreign'),
 ('Z0','Saint Barthelemy','foreign'),
 ('Z1','Saint Martin','foreign'),
 ('Z2','Serbia','foreign'),
 ('Z3','Timor-Leste','foreign'),
 ('Z4','Canada (Federal Level)','foreign'),
 ('Z5','Montenegro','foreign')
on conflict (code) do update
   set label = excluded.label,
       kind  = excluded.kind;

update edgar_codes
   set source_url = 'https://www.sec.gov/submit-filings/filer-support-resources/edgar-state-country-codes', captured_on = '2026-09-02'
 where source_url is null;

-- serviceable_countries now points at it, so a serviceable code cannot be one
-- EDGAR does not define.
--
-- Guarded because ADD CONSTRAINT has no IF NOT EXISTS and every script here
-- must be safe to re-run.
do $$
begin
    if not exists (
        select 1 from pg_constraint
         where conname = 'serviceable_countries_code_fk'
           and conrelid = 'serviceable_countries'::regclass
    ) then
        alter table serviceable_countries
            add constraint serviceable_countries_code_fk
            foreign key (edgar_code) references edgar_codes (code);
    end if;
end $$;
